version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - db_data:/c/github/docker-data/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    

volumes:
    db_data: {}